const data = {
  "success": true,
  "phone": "",
  "data": [
    {
      "store_image": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1594803751-California%20Burrito_skanda.png",
      "image_url": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1594803751-California%20Burrito_skanda.png",
      "name": "California Burrito 8861158181",
      "merchant_name": "California Burrito 8861158181",
      "is_available": true,
      "address_line_1": "Whitefield Main Road, Pattandur Agrahara, Whitefield",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 2.63,
      "start_time": "12:01 AM",
      "end_time": "11:55 PM",
      "offers_count": 2,
      "mid": "1617B52C",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "8861158181",
      "b_type": 3,
      "star_invested": ""
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "Sri Krishna Daily Shop1",
      "merchant_name": "Sri Krishna Daily Shop1",
      "is_available": true,
      "address_line_1": "Seetharampalya - Hoodi Road, Basavanna Nagar, Hoodi",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 3.04,
      "start_time": "12:00 AM",
      "end_time": "11:55 PM",
      "offers_count": 0,
      "mid": "",
      "is_catalogued": false,
      "is_account_details": true,
      "merchant_phone": "",
      "b_type": 7,
      "star_invested": ""
    },
    {
      "store_image": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1586663907-The%20Green.png",
      "image_url": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1586663907-The%20Green.png",
      "name": "Greens Fresh Mart ",
      "merchant_name": "Greens Fresh Mart ",
      "is_available": true,
      "address_line_1": "Brigade Metropolis",
      "address_line_2": "Bangalore",
      "distance": 3.89,
      "start_time": "12:00 AM",
      "end_time": "11:59 PM",
      "offers_count": 0,
      "mid": "A2B57BC7",
      "is_catalogued": false,
      "is_account_details": true,
      "merchant_phone": "1999900015",
      "b_type": 7,
      "star_invested": "0"
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "Ritus 7676216824",
      "merchant_name": "Ritus 7676216824",
      "is_available": true,
      "address_line_1": "Brigade Metropolis, Garudachar Palya, Mahadevapura",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 3.9,
      "start_time": "03:41 AM",
      "end_time": "11:41 PM",
      "offers_count": 0,
      "mid": "6541129C",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "7676216824",
      "b_type": 3,
      "star_invested": ""
    },
    {
      "store_image": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1584366598-Masala%20Chai.png",
      "image_url": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1584366598-Masala%20Chai.png",
      "name": "Masala Chai",
      "merchant_name": "Masala Chai",
      "is_available": true,
      "address_line_1": "Bengaluru, Karnataka 560048, India",
      "address_line_2": ".",
      "distance": 4.98,
      "start_time": "08:00 AM",
      "end_time": "08:00 PM",
      "offers_count": 0,
      "mid": "19317CC8",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "5000005999",
      "b_type": 3,
      "star_invested": "0"
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "A1 Stores",
      "merchant_name": "A1 Stores",
      "is_available": true,
      "address_line_1": "Thotapalyam",
      "address_line_2": "Ongole, Prakasam, Andhra Pradesh, India",
      "distance": 7.21,
      "start_time": "09:00 AM",
      "end_time": "11:56 PM",
      "offers_count": 0,
      "mid": "8118A1B1",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "9494749412",
      "b_type": 7,
      "star_invested": ""
    },
    {
      "store_image": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1594900207-Waffle%20Store.png",
      "image_url": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1594900207-Waffle%20Store.png",
      "name": "Waffle Stories 9886737467",
      "merchant_name": "Waffle Stories 9886737467",
      "is_available": true,
      "address_line_1": "Waffle Stories, Orion Mall, Rajajinagar",
      "address_line_2": "Bengaluru, Karnataka, India",
      "distance": 7.21,
      "start_time": "12:01 AM",
      "end_time": "11:59 PM",
      "offers_count": 0,
      "mid": "18C5D2B9",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "9886737467",
      "b_type": 3,
      "star_invested": ""
    },
    {
      "store_image": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1593242072-Prestege-lifestyle_logo.png",
      "image_url": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1593242072-Prestege-lifestyle_logo.png",
      "name": "Prestige Lifestyle Hennur 7676216825",
      "merchant_name": "Prestige Lifestyle Hennur 7676216825",
      "is_available": true,
      "address_line_1": "Crestron, 1st Cross Road, Hbr Layout 4th Block, Hbr Layout",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 13.13,
      "start_time": "01:00 AM",
      "end_time": "11:42 PM",
      "offers_count": 0,
      "mid": "25BCABC4",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "7676216825",
      "b_type": 3,
      "star_invested": ""
    },
    {
      "store_image": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1592532779-download.png",
      "image_url": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1592532779-download.png",
      "name": "Joy Kisan Domlur 9739671602",
      "merchant_name": "Joy Kisan Domlur 9739671602",
      "is_available": true,
      "address_line_1": "Domlur I Stage, Domlur Village, Domlur",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 15.89,
      "start_time": "12:00 AM",
      "end_time": "11:57 PM",
      "offers_count": 0,
      "mid": "84484471",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "9739671602",
      "b_type": 7,
      "star_invested": ""
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "Vikas Super Market",
      "merchant_name": "Vikas Super Market",
      "is_available": true,
      "address_line_1": "3, 7th Cross Road, Postal Colony, Sanjaynagar",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 17.96,
      "start_time": "06:30 AM",
      "end_time": "11:31 PM",
      "offers_count": 0,
      "mid": "823A2423",
      "is_catalogued": false,
      "is_account_details": true,
      "merchant_phone": "9111231111",
      "b_type": 7,
      "star_invested": ""
    },
    {
      "store_image": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1578729085-the%20world%20cafe.png",
      "image_url": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1578729085-the%20world%20cafe.png",
      "name": "The World Cafe By Sheraton - Kevins 9916057000",
      "merchant_name": "The World Cafe By Sheraton - Kevins 9916057000",
      "is_available": true,
      "address_line_1": "Vr Bangalore, The Hive L6",
      "address_line_2": "White Field Road",
      "distance": 19.37,
      "start_time": "12:00 AM",
      "end_time": "11:59 PM",
      "offers_count": 0,
      "mid": "251A6598",
      "is_catalogued": true,
      "is_account_details": false,
      "merchant_phone": "9916057000",
      "b_type": 3,
      "star_invested": "0"
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "Your Mart 8861105252",
      "merchant_name": "Your Mart 8861105252",
      "is_available": true,
      "address_line_1": "Your Mart, 1st Cross, 1st Phase Girinagar, Ii Phase, Banashankari Stage I, Banashankari, Bengaluru, Karnataka, India",
      "address_line_2": ".",
      "distance": 19.96,
      "start_time": "06:00 AM",
      "end_time": "11:55 PM",
      "offers_count": 0,
      "mid": "AADA9B72",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "8861105252",
      "b_type": 7,
      "star_invested": ""
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "123 Store",
      "merchant_name": "123 Store",
      "is_available": true,
      "address_line_1": "20, 5th Main Road, Govindaraja Nagar Ward, Govindarajanagar, Vijayanagar",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 20.8,
      "start_time": "06:00 AM",
      "end_time": "10:00 PM",
      "offers_count": 0,
      "mid": "476267A7",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "9444444444",
      "b_type": 3,
      "star_invested": "grocery"
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "90 Store",
      "merchant_name": "90 Store",
      "is_available": true,
      "address_line_1": "20, 5th Main Road, Govindaraja Nagar Ward, Govindarajanagar, Vijayanagar",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 20.8,
      "start_time": "06:00 AM",
      "end_time": "10:00 PM",
      "offers_count": 0,
      "mid": "3D76D5A8",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "9333333333",
      "b_type": 3,
      "star_invested": "grocery"
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "10 Store",
      "merchant_name": "10 Store",
      "is_available": true,
      "address_line_1": "20, 5th Main Road, Govindaraja Nagar Ward, Govindarajanagar, Vijayanagar",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 20.8,
      "start_time": "06:00 AM",
      "end_time": "10:00 PM",
      "offers_count": 0,
      "mid": "D1D2482A",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "9222222222",
      "b_type": 3,
      "star_invested": "grocery"
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "99 Store",
      "merchant_name": "99 Store",
      "is_available": true,
      "address_line_1": "20, 5th Main Road, Govindaraja Nagar Ward, Govindarajanagar, Vijayanagar",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 20.8,
      "start_time": "10:00 AM",
      "end_time": "11:00 PM",
      "offers_count": 0,
      "mid": "16A23AAB",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "9123123123",
      "b_type": 3,
      "star_invested": "grocery"
    },
    {
      "store_image": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1578738986-Waffle%20Store.png",
      "image_url": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1578738986-Waffle%20Store.png",
      "name": "Waffle Stories Anjans 7676216846",
      "merchant_name": "Waffle Stories Anjans 7676216846",
      "is_available": true,
      "address_line_1": "156, Ada Bazar",
      "address_line_2": "Indore, Indore, Madhya Pradesh, India",
      "distance": 1102.46,
      "start_time": "12:00 AM",
      "end_time": "11:59 PM",
      "offers_count": 0,
      "mid": "55737789",
      "is_catalogued": true,
      "is_account_details": false,
      "merchant_phone": "7676216846",
      "b_type": 3,
      "star_invested": "0"
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "Restaurant 2",
      "merchant_name": "Restaurant 2",
      "is_available": false,
      "address_line_1": "Unnamed Road, Brigade Metropolis, Garudachar Palya, Mahadevapura",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 3.9,
      "start_time": "03:34 PM",
      "end_time": "11:34 PM",
      "offers_count": 0,
      "mid": "A5623C28",
      "is_catalogued": false,
      "is_account_details": true,
      "merchant_phone": "8073409996",
      "b_type": 3,
      "star_invested": ""
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "Restaurant 3",
      "merchant_name": "Restaurant 3",
      "is_available": false,
      "address_line_1": "Unnamed Road, Brigade Metropolis, Garudachar Palya, Mahadevapura",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 3.9,
      "start_time": "03:39 PM",
      "end_time": "12:39 PM",
      "offers_count": 0,
      "mid": "C85C48C5",
      "is_catalogued": false,
      "is_account_details": true,
      "merchant_phone": "7676216821",
      "b_type": 3,
      "star_invested": ""
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "Restaurant",
      "merchant_name": "Restaurant",
      "is_available": false,
      "address_line_1": "Unnamed Road, Brigade Metropolis, Garudachar Palya, Mahadevapura",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 3.9,
      "start_time": "03:22 PM",
      "end_time": "08:22 PM",
      "offers_count": 0,
      "mid": "83318874",
      "is_catalogued": false,
      "is_account_details": true,
      "merchant_phone": "9999999991",
      "b_type": 3,
      "star_invested": ""
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "Hotel",
      "merchant_name": "Hotel",
      "is_available": false,
      "address_line_1": "Unnamed Road, Brigade Metropolis, Garudachar Palya, Mahadevapura",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 3.9,
      "start_time": "03:24 PM",
      "end_time": "11:24 PM",
      "offers_count": 0,
      "mid": "DC8B15D8",
      "is_catalogued": false,
      "is_account_details": true,
      "merchant_phone": "9999999992",
      "b_type": 3,
      "star_invested": ""
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "Restaurant 4",
      "merchant_name": "Restaurant 4",
      "is_available": false,
      "address_line_1": "Unnamed Road, Brigade Metropolis, Garudachar Palya, Mahadevapura",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 3.9,
      "start_time": "03:40 PM",
      "end_time": "11:40 PM",
      "offers_count": 0,
      "mid": "C2464191",
      "is_catalogued": false,
      "is_account_details": true,
      "merchant_phone": "7676216823",
      "b_type": 3,
      "star_invested": ""
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "Restaurant 12",
      "merchant_name": "Restaurant 12",
      "is_available": false,
      "address_line_1": "Unnamed Road, Brigade Metropolis, Garudachar Palya, Mahadevapura",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 3.9,
      "start_time": "03:44 PM",
      "end_time": "11:44 PM",
      "offers_count": 0,
      "mid": "7A849931",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "8431244396",
      "b_type": 3,
      "star_invested": ""
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "Ankush General Stores",
      "merchant_name": "Ankush General Stores",
      "is_available": false,
      "address_line_1": "Brigade Metropolis, Garudachar Palya, Mahadevapura",
      "address_line_2": "Bengaluru, Bangalore Urban, Karnataka, India",
      "distance": 4,
      "start_time": "09:00 PM",
      "end_time": "11:01 PM",
      "offers_count": 0,
      "mid": "",
      "is_catalogued": false,
      "is_account_details": true,
      "merchant_phone": "",
      "b_type": 7,
      "star_invested": ""
    },
    {
      "store_image": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1587629890-oyeti_grocery.jpg",
      "image_url": "https://ttoyeti.s3.amazonaws.com/storeimages/staging/1587629890-oyeti_grocery.jpg",
      "name": "Divya Stores",
      "merchant_name": "Divya Stores",
      "is_available": false,
      "address_line_1": "I-block, Akme Ballet Inner Road, Chinappa Layout, Mahadevapura, Bengaluru, Karnataka 560037, India",
      "address_line_2": "White Field Road",
      "distance": 4.18,
      "start_time": "10:00 AM",
      "end_time": "11:00 PM",
      "offers_count": 0,
      "mid": "7342B422",
      "is_catalogued": false,
      "is_account_details": true,
      "merchant_phone": "9898989859",
      "b_type": 3,
      "star_invested": "0"
    },
    {
      "store_image": "",
      "image_url": "",
      "name": "Bhoom Chicken",
      "merchant_name": "Bhoom Chicken",
      "is_available": false,
      "address_line_1": "Burger King, 10th Cross Rd, Rajajinagar, Bengaluru, Karnataka, India",
      "address_line_2": ".",
      "distance": 19.33,
      "start_time": "09:00 AM",
      "end_time": "10:00 PM",
      "offers_count": 0,
      "mid": "",
      "is_catalogued": true,
      "is_account_details": true,
      "merchant_phone": "",
      "b_type": 3,
      "star_invested": ""
    }
  ]
}

export default data;